### ISSUE TITLE
Adding non-free resources?

### ISSUE THREAD

**Issue by ChadoNihi** [henryaj/awesome-effective-altruism#2]
I think Phil Torres' [Morality, Foresight, and Human Flourishing: An Introduction to Existential Risks](https://www.risksandreligion.org/) should be added to **Existential risk** section. However, AFAIK the book is not available for free. Do we list paid materials?

**Comment by henryaj** [comment]
That's fine. I've listed books, and I don't think it's expected that books are generally free.
