### ISSUE TITLE
Create a section for funds + add REG Fund

### ISSUE THREAD

**Issue by ChadoNihi** [henryaj/awesome-effective-altruism#6]
[Effective Altruism Funds](https://app.effectivealtruism.org/funds) currently occupies a special mention in *Popular Charities* section. I propose to create a section for funds and add [REG Fund](https://reg-charity.org/fund/).

**Comment by henryaj** [comment]
Sure - happy for you to open a PR!

**Comment by henryaj** [comment]
Actually, this is pretty straightforward; will do it myself.
